Added post about notebook submission tutorial
USRSE/usrse23 pull request #19
Opened 2023-03-03 01:02 UTC by nicole-brewer

## Checklist:

- [ ] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [ ] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves @jscubida

2023-03-06 18:23 UTC, mrmundt requested changes

2023-03-06 18:23 UTC, mrmundt commented on _posts/2023-03-03-notebook-submission-tutorial.md
> +**Time:** 3:00 PM EDT, 2:00 PM CDT, 1:00 MDT, 12:00 PM MST
The times here don't make sense to me. Everything is in DT until 12PM MST?

2023-03-06 18:23 UTC, mrmundt commented on _posts/2023-03-03-notebook-submission-tutorial.md
> +[Submission of computational notebooks](https://us-rse.org/usrse23/submissions/notebooks/) are due Monday, May 1, 2023. To account for the broad variety of use cases for notebooks, we are accepting s
Can you turn this into two separate paragraphs / maybe make a bulleted list of what attendees should expect to hear or learn?

2023-03-06 18:34 UTC, torwhite commented on _posts/2023-03-03-notebook-submission-tutorial.md
> +**Time:** 3:00 PM EDT, 2:00 PM CDT, 1:00 MDT, 12:00 PM MST
Arizona doesn't observe daylight savings, so this makes sense. Maybe we should add PDT though, so as not to leave out the Californians

2023-03-14 14:11 UTC, mrmundt commented
@nicole-brewer - Can you please apply the requested changes? Thank you!

2023-03-17 01:17 UTC, nicole-brewer commented
Requested changes made!

2023-03-17 17:25 UTC, mrmundt approved these changes

2023-03-17 17:30 UTC, merged