Update Dockerfile and Readme to support local container-based development
USRSE/usrse23 pull request #8
Opened 2023-02-14 21:25 UTC by manning-ncsa

## Description

This update fixes the Dockerfile and associated Gemfile to allow a successful container image build. Additionally, instructions are added to the `Readme.md` file describing how to build, run, and develop code in the local container.

## Motivation and Context

This update addresses issue #7 . Supporting a Docker-based development workflow will enable more collaborators to run the code in a reproducible way in order to better address content changes in future pull requests.

## Checklist:

- [ ] I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [x] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot

2023-02-14 21:26 UTC, manning-ncsa commented on Gemfile
> +gem 'faraday-retry', '2.0.0'
This addition was due to a suggestion that displayed during the `bundle install` step.

2023-02-14 21:27 UTC, manning-ncsa commented on Dockerfile
> +FROM jekyll/jekyll:3.8
The latest jekyll image tag `4` did not seem to work, but I didn't do exhaustive testing to discover why.

2023-02-14 21:39 UTC, mrmundt requested changes

2023-02-14 21:39 UTC, mrmundt commented on README.md
> +Build and run a Docker container to preview the site locally and support a local development workflow.
Please add a link to how to set up Docker on your machine. Not everyone will know what are the "best" instructions to follow.

2023-02-14 21:39 UTC, mrmundt commented on Gemfile
Please try your Dockerfile with the following additions to the Gemfile:

```
gem 'webrick'
```

2023-02-14 21:40 UTC, manning-ncsa commented on README.md
> +Build and run a Docker container to preview the site locally and support a local development workflow.
Oh, right, I forgot. Will do.

2023-02-14 21:42 UTC, jbteves commented on Dockerfile
> +FROM jekyll/jekyll:3.8
Please document this in the dockerfile, along with an error explanation.

2023-02-14 21:42 UTC, manning-ncsa commented on README.md
> +Build and run a Docker container to preview the site locally and support a local development workflow.
https://github.com/USRSE/usrse23/pull/8/commits/9cc870ea5d4b1c5ae6a22d897d4f1acae190edf9

2023-02-14 21:43 UTC, jbteves commented on Gemfile
> +gem 'faraday-retry', '2.0.0'
Please document this in the dockerfile or in #7

2023-02-14 21:44 UTC, mrmundt commented on Gemfile
Reason: It's the only addition I needed to be able to use the Gemfile on my Mac. If that works on Docker as well as locally on a Mac, then I think we have our bases fairly well covered.

2023-02-14 21:53 UTC, manning-ncsa commented on Dockerfile
> +FROM jekyll/jekyll:3.8
I'm not a fan of junking up the Dockerfile with a big comment like that, but if you think that's useful, it's fine with me (https://github.com/USRSE/usrse23/pull/8/commits/89e365bbed8130dccf0e18c779b653db5699a1a7)

2023-02-14 21:53 UTC, manning-ncsa commented on Gemfile
Added in https://github.com/USRSE/usrse23/pull/8/commits/0b3df9ac257f151518e08785c1d1566db87d7e15 and it builds and runs successfully.

2023-02-14 21:55 UTC, mrmundt commented on Gemfile
Thanks!

2023-02-14 22:02 UTC, mrmundt approved these changes

2023-02-14 22:04 UTC, manning-ncsa commented
As a test of the development workflow, I merged the branch https://github.com/lbianchi-lbl/usrse23/tree/notebook-submissions into this one locally and was able to load the new page at `http://0.0.0.0:4000/usrse23/pages/notebook-submissions/index.html` after rebuilding.

2023-02-14 22:46 UTC, manning-ncsa commented
@mrmundt Your merge of #3 produced a conflict in the Gemfile. These versions of the file are completely different, so I don't know what to do. Retain all the lines from each?

2023-02-14 22:49 UTC, mrmundt commented
Oh, whoops, nope - keep the file you had. It's the right one.

2023-02-14 22:49 UTC, manning-ncsa commented
I rebuilt the container with the proposed Gemfile conflict resolution in commit https://github.com/USRSE/usrse23/pull/8/commits/9d2f1f76b26ed9c63dcb5a2f89129a8c91b2997c and it works

2023-02-14 23:05 UTC, mrmundt commented
@manning-ncsa - Can you try with 50307cd3eab2246b5d280e413b60a1a551b16484?

2023-02-15 14:38 UTC, lbianchi-lbl commented
FWIW - I've used the instructions and files from 50307cd and they seem to work fine.

2023-02-15 14:40 UTC, merged